## 1. Fixed size tensors

In [2]:
import tensorflow as tf

2022-01-17 17:26:22.800064: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0


In [5]:
# Create a zero-filled tensor
row_dim, col_dim = 3, 3
zero_tsr = tf.zeros(shape=[row_dim, col_dim], dtype=tf.float32)

In [6]:
# Create a one-filled tensor
ones_tsr = tf.ones([row_dim, col_dim])

In [7]:
# Create a constant-filled tensor
filled_tsr = tf.fill([row_dim, col_dim], 42)

In [8]:
# Create a tensor out of an existing constant
constant_tsr = tf.constant([1, 2, 3])

## 2. Tensors of similar shape

In [9]:
zeros_similar = tf.zeros_like(constant_tsr)
ones_similar = tf.ones_like(constant_tsr)

## 3. Sequence tensors

In [10]:
linear_tsr = tf.linspace(start=0.0, stop=1.0, num=3)

In [11]:
print(linear_tsr)

tf.Tensor([0.  0.5 1. ], shape=(3,), dtype=float32)


In [12]:
integer_seq_tsr = tf.range(start=6, limit=15, delta=3)

In [13]:
print(integer_seq_tsr)

tf.Tensor([ 6  9 12], shape=(3,), dtype=int32)


## 4. Randoms tensors

In [14]:
randunif_tsr = tf.random.uniform([row_dim, col_dim], minval=0, maxval=1)

In [15]:
print(randunif_tsr)

tf.Tensor(
[[0.9193058  0.82627606 0.86051524]
 [0.39540625 0.9212284  0.15795386]
 [0.10390413 0.6723801  0.5303372 ]], shape=(3, 3), dtype=float32)


In [16]:
randunif_tsr = tf.random.uniform([row_dim, col_dim], minval=0.9, maxval=1.1)

In [17]:
print(randunif_tsr)

tf.Tensor(
[[1.0922229  0.9048704  1.0926778 ]
 [1.0705576  1.0555116  0.9668028 ]
 [1.0290012  0.92316383 0.971211  ]], shape=(3, 3), dtype=float32)


In [18]:
randnorm_tsr = tf.random.normal([row_dim, col_dim], mean=0.0, stddev=1.0)

In [19]:
runcnorm_tsr = tf.random.truncated_normal([row_dim, col_dim], mean=0.0, stddev=1.0)

In [20]:
shuffled_output = tf.random.shuffle(input_tensor)
cropped_output = tf.image.random_crop(input_tensor, crop_size)

NameError: name 'input_tensor' is not defined

In [22]:
height, width = (64, 64)
my_image = tf.random.uniform([height, width, 3], minval=0, maxval=255, dtype=tf.int32)
cropped_image = tf.image.random_crop(my_image, [height//2, width//2, 3])

## How it works...

In [24]:
my_var = tf.Variable(tf.zeros([row_dim, col_dim]))