The activations live in the neural network (nn) library) in TensorFlow. Besides using built-in activation functions, we can also design our own using tensorFlow operations. We can import the predefined activation functions (from tensorflow import nn) or be explicit and write nn in our function calls. Here, we'll choose to be explicit with each function call. 

## 1. ReLU

In [1]:
import tensorflow as tf

2022-01-18 08:16:27.179676: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0


In [2]:
print(tf.nn.relu([-3., 3., 10.]))

tf.Tensor([ 0.  3. 10.], shape=(3,), dtype=float32)


2022-01-18 08:16:46.195659: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2022-01-18 08:16:46.258788: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-01-18 08:16:46.259154: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:2d:00.0 name: GeForce RTX 2070 SUPER computeCapability: 7.5
coreClock: 1.785GHz coreCount: 40 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.29GiB/s
2022-01-18 08:16:46.259168: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2022-01-18 08:16:46.268212: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2022-01-18 08:16:46.268237: I tensorflow/stream_executor/plat

## 2. ReLU 6

In [3]:
print(tf.nn.relu6([-3., 3., 10.]))

tf.Tensor([0. 3. 6.], shape=(3,), dtype=float32)


## 3. Sigmoid

In [4]:
print(tf.nn.sigmoid([-1., 0., 1.]))

tf.Tensor([0.26894143 0.5        0.73105854], shape=(3,), dtype=float32)


## 4. Hyper tangent

In [5]:
print(tf.nn.tanh([-1., 0., 1.]))

tf.Tensor([-0.7615942  0.         0.7615942], shape=(3,), dtype=float32)


## 5. Softsign function

In [6]:
print(tf.nn.softsign([-1., 0., 1.]))

tf.Tensor([-0.5  0.   0.5], shape=(3,), dtype=float32)


## 6. Softplus function

In [8]:
print(tf.nn.softplus([-1., 0., 1.]))

tf.Tensor([0.31326172 0.6931472  1.3132616 ], shape=(3,), dtype=float32)


## 7. ELU

In [9]:
print(tf.nn.elu([-1., 0., 1]))

tf.Tensor([-0.6321205  0.         1.       ], shape=(3,), dtype=float32)


## 8. Further resources...

More activations can be found on the Keras activation page: https://www.tensorflow.org/api_docs/python/tf/keras/activations

## There's more...

We can easily create custom activations such as Swish, which is x\*sigmoid(x), which can be used as a more performing replacement for ReLU activations in image and tabular data problems:

In [10]:
def swish(x):
    return x * tf.nn.sigmoid(x)

print(swish([-1., 0., 1.]))

tf.Tensor([-0.26894143  0.          0.73105854], shape=(3,), dtype=float32)
