## 1. Creating matrices

In [5]:
import tensorflow as tf
import numpy as np

In [6]:
identity_matrix = tf.linalg.diag([1.0, 1.0, 1.0])
A = tf.random.truncated_normal([2, 3])
B = tf.fill([2, 3], 5.0)
C = tf.random.uniform([3, 2])
D = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]]), dtype = tf.float32)

In [7]:
print(identity_matrix)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [8]:
print(A)

tf.Tensor(
[[ 0.4589003   0.96595794 -1.1089929 ]
 [ 0.9904659   0.3910998  -1.185653  ]], shape=(2, 3), dtype=float32)


In [9]:
print(B)

tf.Tensor(
[[5. 5. 5.]
 [5. 5. 5.]], shape=(2, 3), dtype=float32)


In [10]:
print(C)

tf.Tensor(
[[0.26230574 0.34384537]
 [0.8383665  0.63503003]
 [0.5704981  0.54587984]], shape=(3, 2), dtype=float32)


In [11]:
print(D)

tf.Tensor(
[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]], shape=(3, 3), dtype=float32)


## 2. Addition, subtraction, multiplication

In [12]:
print(A + B)

tf.Tensor(
[[5.4589005 5.965958  3.891007 ]
 [5.990466  5.3911    3.814347 ]], shape=(2, 3), dtype=float32)


In [13]:
print(B - B)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [14]:
print(tf.matmul(B, identity_matrix))

2022-01-17 17:57:48.495632: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11


tf.Tensor(
[[5. 5. 5.]
 [5. 5. 5.]], shape=(2, 3), dtype=float32)


2022-01-17 17:57:48.762215: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11


In [15]:
print(tf.multiply(D, identity_matrix))

tf.Tensor(
[[ 1.  0.  0.]
 [-0. -7. -0.]
 [ 0.  0. -2.]], shape=(3, 3), dtype=float32)


## 3. The transpose

In [16]:
print(tf.transpose(C))

tf.Tensor(
[[0.26230574 0.8383665  0.5704981 ]
 [0.34384537 0.63503003 0.54587984]], shape=(2, 3), dtype=float32)


## 4. Determinant

In [17]:
print(tf.linalg.det(D))

2022-01-17 17:59:40.738467: I tensorflow/core/util/cuda_solvers.cc:180] Creating CudaSolver handles for stream 0x50ad2b0
2022-01-17 17:59:40.739047: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11


tf.Tensor(-38.0, shape=(), dtype=float32)


2022-01-17 17:59:41.507027: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11


## 5. Inverse

In [22]:
print(tf.linalg.inv(D))

tf.Tensor(
[[-0.5        -0.5        -0.5       ]
 [ 0.15789473  0.05263159  0.21052632]
 [ 0.3947369   0.13157895  0.02631579]], shape=(3, 3), dtype=float32)


## 6. Decompositions

In [23]:
print(tf.linalg.cholesky(identity_matrix))

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


## 7. Eigenvalues and eigenvectors

In [24]:
print(tf.linalg.eigh(D))

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-10.659075  ,  -0.22750685,   2.8865821 ], dtype=float32)>, <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.21749547,  0.632501  ,  0.74339634],
       [ 0.84526515,  0.25879973, -0.46749276],
       [-0.4880805 ,  0.73004454, -0.4783432 ]], dtype=float32)>)
